backend = "glx";
vsync = true;

# Transparency
inactive-opacity = 0.7;
active-opacity = 0.8;
frame-opacity = 0.8;
inactive-opacity-override = false;

# Firefox exception — force full opacity
opacity-rule = [
  "100:class_g = 'org.mozilla.firefox'",
];

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Blur
blur-method = "dual_kawase";
blur-strength = 3;

blur-background-exclude = [
  "class_g = 'org.mozilla.firefox'"
];

# Corner Rounding
corner-radius = 8;
